news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('grappelli/', include('grappelli.urls')),
	path('titles/', include("parse.urls")),
    path('admin/', admin.site.urls),
]

parse/urls.py
from django.urls import path

from . import views


app_name  = 'parse'
urlpatterns = [
	path('', views.index, name = "index"),
	path('<int:article_id>/', views.detail, name = "detail"),
	path('<int:article_id>/leave_comment', views.leave_comment, name = "leave_comment"),
]

parse/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField('article title', max_length = 200)
    description = models.TextField('description', max_length = 9000)
    image = models.CharField('image', max_length = 200)
    link = models.CharField('link', max_length = 200)
    date = models.CharField('date', max_length = 200)


    def __str__(self):
        return self.title


    class Meta:
        verbose_name = "Article"
        verbose_name_plural = "Articles"
        

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE)
    author_name = models.CharField('author name', max_length = 50)
    comment_text = models.CharField('comment text', max_length = 200)

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"

parse/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render

from django.urls import reverse

from .models import Article

def index(request):
	articles_list = Article.objects.order_by('-date')
	return render(request, 'parse/list.html', {'articles_list': articles_list})

def detail(request, article_id):
	try:
		a = Article.objects.get(id = article_id)
	except:
		raise Http404("Page not found")

	latest_comments_list = a.comment_set.order_by('-id')[:10]
	return render(request, 'parse/detail.html', {'article': a, 'latest_comments_list': latest_comments_list})


def leave_comment(request, article_id):
	try:
		a = Article.objects.get(id = article_id)
	except:
		raise Http404("Page not found")

	a.comment_set.create(author_name = request.POST["name"], comment_text = request.POST["text"])

	return HttpResponseRedirect( reverse('parse:detail', args = (a.id,)) )

news/templates/base.html
<!DOCTYPE html>
<html lang = "en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}My Site{% endblock %}</title>
</head>
<body>

	{% block content %}{% endblock %}
</body>
</html>

news/templates/parse/detail.html
{% extends 'base.html' %}

{% block title %}{{article.title}}{% endblock %}

{% block content %}
	
	<h2>{{article.title}}</h2>
	<img src={{article.image}} width = 520 height = 384 align="left" alt={{article.image}}><br>
	<p>{{article.description}}</p>
	<a href={{article.link}}>Learn more</a><br>
	Publish date: <em>{{article.date}}</em><br>

	<hr>

	{% if latest_comments_list %}
		{% for comment in latest_comments_list %}
			<p>
				<strong>{{comment.author_name}}</strong><br>
				{{comment.comment_text}}
			</p>  

		{% endfor %}

	{% else %}
		There is no comments. Become first =)
	{% endif %}

	<hr>

	<form action="{% url 'parse:leave_comment' article.id %}" method="POST">
		
		{% csrf_token %}

		<input type="text" required placeholder="Your name" name="name"><br>
		<textarea name="text" required="" placeholder="Comment Text" cols="30" rows="10"></textarea><br>

		<button type="submit">Leave comment</button>
	</form>



{% endblock %}

news/templates/parse/list.html
{% extends 'base.html' %}

{% block title %}Last Articles{% endblock %}

{% block content %}
	
	{% if articles_list %}
		{% for article in articles_list %}
			<a href="{% url 'parse:detail' article.id %}">{{article.title}}</a><br>
			<img src={{article.image}} width = 520 height = 384 align="left" alt={{article.image}}><br>
			Publish date: <em>{{article.date}}</em><br>
			<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
		{% endfor %}

	{% else %}
		There is no articles )=
	{% endif %}

	{% if latest_comments_list %}
		{% for comment in latest_comments_list %}
			{{comment.author_name}}  --  {{comment.comment_text}}
		{% endfor %}

	{% else %}
		There is no comments. Become first =)
	{% endif %}

{% endblock %}